### ISSUE TITLE
Resize "withoutEnlargement" option not working correctly

### ISSUE THREAD

**Issue by ezekg** [vseventer/sharp-cli#11]
I'm trying to resize a directory of png images, but some of the images are already below my specified width/height, resulting in them being either cropped (if `--max` isn't provided) or scaled up.

For example,

```
sharp -i src/images/*.png -o dist/images resize 640 640 --withoutEnlargement --max -- --quality 90 --optimize
```

results in all images being scaled up to `640`, regardless of whether or not some of the images are already smaller than `640`, even though I specified the `--withoutEnlargement` flag.

Any ideas?

**Comment by ezekg** [comment]
It looks like [this line](https://github.com/vseventer/sharp-cli/blob/57a4fcee82c4372559ba32142db4b1428ea43f64/cmd/resize.js#L137-L139) never applies `sharp.withoutEnlargement()` when the option is enabled.

**Comment by vseventer** [comment]
@ezekg I misinterpreted sharp's documentation stating `withoutEnlargement` defaults to `true` - this only holds if the flag is actually present.

**Comment by ezekg** [comment]
No problem! Thanks for the quick fix. 🙂
