### ISSUE TITLE
expo optimize error 

### ISSUE THREAD

**Issue by thameemk612** [vseventer/sharp-cli#19]
"expo optimize" shows below error , even though after installing sharp-cli

Optimizing ./assets/icon.png
This command requires version 1.10.0 of `sharp-cli`. 
You can install it using `npm install -g sharp-cli@1.10.0`. 

For prerequisites, see: https://sharp.dimens.io/en/stable/install/#prerequisites
Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by Saneesh** [comment]
Same here

**Comment by thameemk612** [comment]
Can you please run the below command . I got it solved 
sudo npm install --unsafe-perm --verbose -g sharp-cli or 
sudo npm install --unsafe-perm --verbose -g sharp-cli --save

Source : https://github.com/nodejs/node-gyp/issues/454

**Comment by Saneesh** [comment]
Hello @thameemk612,
Thank you for your reply
Successfully I have executed that command, but still I'm getting the following error.
I have tried like this too: `sudo npm install --unsafe-perm --verbose -g sharp-cli@1.10.0 --save`

```
$expo optimize                    
This will overwrite the original assets.
Optimizing assets...
Optimizing ./assets/icon.png
This command requires version 1.10.0 of `sharp-cli`. 
You can install it using `npm install -g sharp-cli@1.10.0`. 

For prerequisites, see: https://sharp.dimens.io/en/stable/install/#prerequisites
Set EXPO_DEBUG=true in your env to view the stack trace.
```

Regards,
Saneesh.

**Comment by vseventer** [comment]
Hi @Saneesh - this appears to be an issue with `expo` rather than with the CLI itself. I recommend opening an issue [here](https://github.com/expo/expo-cli/issues).
