### ISSUE TITLE
resize but keep proportion

### ISSUE THREAD

**Issue by oupala** [vseventer/sharp-cli#23]
I want to resize a serie of images that are in a directory. I'm using the following command:

```bash
npx sharp-cli resize 800 800 --withoutEnlargement true --optimise true --progressive true --withMetadata false --format input --input *.jpg --output "out/"
```

Images smaller than 800x800 are just copied in the output directory.

But bigger image are resized to 800x800 (square). What I wanted is that when an image is resized, its ratio is keeped: 800x600 for a landscape, and 600x800 for a portrait.

Have I missed something?

When I have a look at the documentation, I'm not sure if I have to use a *height* or *width* parameter or not:

> sharp resize <width> [height]
> 
>   --height              Number of pixels wide the resultant image should be [nombre]
>   --width               Number of pixels high the resultant image should be [nombre]

**Comment by oupala** [comment]
I was looking for something like this imagemagick command:

> convert -resize 640x640\> *.jpg "${pattern}-%d.jpg"

**Comment by vseventer** [comment]
Try using the `--fit inside` option - see https://sharp.pixelplumbing.com/en/stable/api-resize/#resize

**Comment by oupala** [comment]
Thanks a lot, that was what I was looking for.

Is there a way to overwrite the input file, or to set a pattern for naming the out files (something like ${original_name}-resized.jpg)?

All what I saw on the README file is that sharp-cli is made for one file at a time (even if bash car use jokers to change multiple files at a time).

**Comment by vseventer** [comment]
You can use [url-templates](https://www.npmjs.com/package/url-template) for this - for example `sharp resize 800 600 --fit inside -o ./dest/{name}.{ext}`. Batch processing is supported.

**Comment by oupala** [comment]
Is there a way to use sharp and url-templates directly in a CLI?

Or is it mandatory to create a js script to use both of them in cunjunction?

**Comment by vseventer** [comment]
Yes, you can use this right from the CLI - see my last reply for an example.

**Comment by oupala** [comment]
You mean, I juste have to install url-templates globally, then to enter the following command:

```bash
sharp resize 800 600 --fit inside -i ./src/*.jpg -o ./dest/{name}{ext}
```

and `{name}` and `{ext}` will be automatically defined?

It is still no possible to overwrite the source file with this solution, right?

**Comment by vseventer** [comment]
Everything already comes with the CLI - just try and run the command in my example above.

**Comment by oupala** [comment]
You're right, I tested it and it works perfectly, impressive!

The only thing I am missing is overwriting. What a pity... I'll have to find a workaround.

**Comment by vseventer** [comment]
The CLI used to be able to do that, but I removed support for it since it led to problems with large files - streams are great for this, but in order to save to the same file, we'll have to store the entire image in memory. I might be able to add a `--overwrite` option in the CLI, with the gotcha that you should use this only for small files.

**Comment by oupala** [comment]
I understand the limitation that you encountered.

But I would be very happy to see this feature back in sharp.

**Comment by vseventer** [comment]
I created this request in #24. Closing this.

**Comment by mathieu-aubin** [comment]
you could pipe output to 'sponge' and save as same file. Otherwise, input file gets destroyed before reading
