### ISSUE TITLE
Support same file for input and output

### ISSUE THREAD

**Issue by vseventer** [vseventer/sharp-cli#24]
# What
Support overwriting the input file.

# Why
We've been historically able to do this, but I removed that feature since it led to errors when processing large files. The node dependency I relied upon back then is no longer maintained, so there might be a better alternative. This is also a user ask in #23.

# How
* `sharp -i file.jpg -o file.jpg`: input file is overwritten with the processed image.
* `sharp -i *.jpg -o ./`: multiple input files are overwritten with processed images.

**Comment by oupala** [comment]
It could also be this way:

```bash
sharp -i --replace *.jpg
```

There should be warning issued if the file is larger than *something* or maybe the warning can be issued every time, whatever big are the files to process.

**Comment by mathieu-aubin** [comment]
Have a look at 'sponge' source code maybe that could help in coding a method/function for same file processing

**Comment by oupala** [comment]
Great news! Do you plan to release a new version with this release?

**Comment by vseventer** [comment]
This is now released. @oupala

**Comment by oupala** [comment]
Maybe this should be documented?

I found how to do that in this issue, but I could not find it in the documentation.

**Comment by oupala** [comment]
I found a problem using this feature: if I want to convert file from a whole tree, all converted files are created at the rool level. Let me explain the problem:

I use the following command: `npx sharp-cli resize 800 800 --format input --fit inside --input ./directory/**/*.jpg --output ./directory/`

If there is a file at `./directory/pictures/DSC0019.jpg`, the converted file will be created at `./directory/DSC0019.jpg`. That means that all subdirectories are flattened to the root level.

Is there a way to avoid such behavior?

**Comment by vseventer** [comment]
You have to use an output template, probably something like `--output "{dir}/{base}"`. Please open separate issue if you keep having issues.
