### ISSUE TITLE
heif error from 1.11.0 on

### ISSUE THREAD

**Issue by tmjoen** [vseventer/sharp-cli#25]
Hi, and first of all thanks for this awesome CLI. It has sped up my thumbnailing process a TON.

There was a regression in my setup when moving from 1.10.0 to 1.11.0

This is the cmd I'm running
```
sharp -i media/images/site/project-gallery/tine-1/a2hlnlcafc.jpg
-o media/images/site/project-gallery/tine-1/xlarge/{name}{ext} 
--quality 85 --palette true --format jpg resize 1900 --withoutEnlargement --fit inside
```

It works fine on 1.10.0, but on 1.11.0 it errors with

```
The heif operation requires libvips to have been installed with support for libheif
Specify --help for available options
```

Thanks!

**Comment by vseventer** [comment]
Thanks for reporting - this seems to be a bug.
