### ISSUE TITLE
allow to process hidden files and hidden directories

### ISSUE THREAD

**Issue by oupala** [vseventer/sharp-cli#28]
Since lasts versions and #26, sharp-cli allows to parse a whole tree and to process files in place (replacing the original file).

However, hidden files and directory are not processed are they are not parsed. They're simply ignored.

I'd love to see sharp-cli able to optimize images that are in a hidden directory.

With bash, I can set how bash behave with setting a specific *shopt* option:

```bash
$ shopt -u dotglob
$ ls docs/**/*.jpg
$
```

```bash
$ shopt -s dotglob
$ ls docs/**/*.jpg
docs/directory/.hidden-image.jpg
docs/.hidden-directory/image.jpg
$
```

Is there a way to set a similar option for sharp-cli? If not, could it be possible to add options to set how sharp-cli behave?

```bash
$ npx sharp-cli --include-hidden-files
$ npx sharp-cli --include-hidden-directory
```

**Comment by vseventer** [comment]
Two options - you can either pass both globs, e.g. `sharp -i docs/**/*.jpg docs/**/.*.jpg`, or use a subcommand, like `sharp -i $(find *.jpg)`.

**Comment by oupala** [comment]
Thanks for your suggestions @vseventer.

I could not use the first option as it would select hidden files, but not hidden directory.

Could I add another blog selector such as `sharp -i docs/**/*.jpg docs/**/.*.jpg docs/**/.*/**/*.jpg` the select also files in hidden directory. But this added blog selector, would not select hidden files inside hidden directory. I should then use `sharp -i docs/**/*.jpg docs/**/.*.jpg docs/**/.*/**/*.jpg docs/**/.*/**/.*.jpg`. This is getting more and more confusing...

The second option seems to be the best for the moment, and here is the command I'm using:

```bash
npx sharp-cli resize 800 800 --withoutEnlargement true --optimise true --progressive true --withMetadata false --format input --fit inside --input $(find ./docs -name *.jpg -or -name *.png) --output "{dir}/{base}"
```

The main advantage is that `find` also search into hidden directories, **but does not find hidden files**. The main issue is that this command works on linux, but should probably fail on windows... The whole process is now platform-dependent, which is not very good.

I still think that it would be a great thing to include a parameter flag in shrap-cli options.

**Comment by vseventer** [comment]
I'm closing this - I don't feel it's a responsibility of `sharp-cli` to filter / modify input files. I recommend using a proper tool focused on globbing files, and pipe the result into the CLI for proper processing.

**Comment by oupala** [comment]
As sharp-cli does support glob input patterns (#27), I think it is now its responsibility to manage how glob input patterns are parsed.

More and more static website generators are using hidden files or directories. It is nowadays a common usecase to optimize all images inside a whole tree, including hidden files and directories.
