### ISSUE TITLE
"Error: Cannot find module" error on GitLab CI

### ISSUE THREAD

**Issue by oupala** [vseventer/sharp-cli#30]
I'm trying to run the following command into a GitLab CI file `.gitlab-ci.yml` :

```bash
npx sharp-cli resize 800 800 --withoutEnlargement true --optimise true --progressive true --withMetadata false --format input --fit inside --input $(find ./docs -name *.jpg -or -name *.png) --output "{dir}/{base}"
```

On my laptop, everything run well:

> $ npx sharp-cli resize 800 800 --withoutEnlargement true --optimise true --progressive true --withMetadata false --format input --fit inside --input $(find ./docs -name *.jpg -or -name *.png) --output "{dir}/{base}"
> info sharp Using cached /home/myuser/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz
> /home/path/to/website/docs/images/photos/sejour.jpg

But inside a GitLab CI pipeline, it fails fast:

> $ npx sharp-cli resize 800 800 --withoutEnlargement true --optimise true --progressive true --withMetadata false --format input --fit inside --input $(find ./docs -name *.jpg -or -name *.png) --output "{dir}/{base}"
internal/modules/cjs/loader.js:964
    throw err;
    ^
> 
> Error: Cannot find module '/root/.npm/_npx/12/lib/node_modules/sharp-cli/node_modules/sharp/install/libvips'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, stat '/root/.npm/_npx/12/lib/node_modules/sharp-cli/node_modules/sharp/.node-gyp/13.3.0'
gyp ERR! System Linux 4.19.0-6-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.npm/_npx/12/lib/node_modules/sharp-cli/node_modules/sharp
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-08T22_44_57_178Z-debug.log
Install for [ 'sharp-cli@latest' ] failed with code 1
Authenticating with credentials from /root/.docker/config.json
ERROR: Job failed: exit code 1

This error might not be specific to `sharp-cli` and maybe more related to GitLab CI, but maybe someone will have a suggestion, or a starting point to look from.

I do not understand why `node-gyp` is into the logs. Is `libvips` being rebuilt on CI while it is simply downloaded on my laptop?

Thanks !

**Comment by vseventer** [comment]
From the looks of it, it appears to be an issue with installing sharp and `libvips` - better to ask on sharps issue tracker for a better answer.

**Comment by oupala** [comment]
You're right. I had `libvips42 8.4.5-1+deb9u1` installed on my laptop using `apt`.

To use `sharp-cli` on GitLab CI, I'll have to get a docker image with npm and libvips.

**Comment by oupala** [comment]
@vseventer I think we should reopen this issue as I can't manage to make sharp-cli to work in a docker container.

Here is the `.gitlab-ci.yml` file that I'm using:

```yaml
pages:
  image: node:latest
  script:
  - apt update && apt install -y libvips42
  - npx sharp-cli resize 800 800 --withoutEnlargement true --optimise true --progressive true --withMetadata false --format input --fit inside --input $(find ./public -name *.jpg -or -name *.png) --output "{dir}/{base}"
```

We can see in the logs that libvips **is** correctly installed:

> Selecting previously unselected package libvips42:amd64.
> Preparing to unpack .../106-libvips42_8.4.5-1+deb9u1_amd64.deb ...
> Unpacking libvips42:amd64 (8.4.5-1+deb9u1) ...

But it ends with an error saying that libvips is not installed:

> $ npx sharp-cli resize 800 800 --withoutEnlargement true --optimise true --progressive true --withMetadata false --format input --fit inside --input $(find ./public -name *.jpg -or -name *.png) --output "{dir}/{base}"
internal/modules/cjs/loader.js:964
    throw err;
    ^
> 
> Error: Cannot find module '/root/.npm/_npx/1426/lib/node_modules/sharp-cli/node_modules/sharp/install/libvips'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, stat '/root/.npm/_npx/1426/lib/node_modules/sharp-cli/node_modules/sharp/.node-gyp/13.3.0'
gyp ERR! System Linux 4.19.0-6-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.npm/_npx/1426/lib/node_modules/sharp-cli/node_modules/sharp
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-12T21_43_42_729Z-debug.log
Install for [ 'sharp-cli@latest' ] failed with code 1
Authenticating with credentials from /root/.docker/config.json
ERROR: Job failed: exit code 1

Does anyone has an idea about why sharp or sharp-cli does not find libvips although it **is** installed?

**Comment by vseventer** [comment]
@oupala I think it would make sense to raise this on the sharp issue tracker - this package doesn't do anything special with libvips.

**Comment by oupala** [comment]
You're right. I'll do that now.
