### ISSUE TITLE
Alpha channel is removed

### ISSUE THREAD

**Issue by janaagaard75** [vseventer/sharp-cli#31]
Putting [this image](https://github.com/janaagaard75/desert-walk/blob/master/assets/50713-transparent.png) through `sharp-cli` makes the semi-transparent pixels opaque, or a least a lot less transparent.

I have tried adding `--alphaQuality 100` and `--quality 100` to the command, but that doesn't help.

(I hope I am reporting this issue the correct place. This is the original issue that I have: <https://github.com/expo/expo-cli/issues/1373>.)

**Comment by vseventer** [comment]
@janaagaard75 What's the full command?

**Comment by janaagaard75** [comment]
`sharp -i ./50713-transparent.png -o ./optimized.png --optimize`, and them trying different combinations including `preserveAlpha` and `quality`.

I am trying to optimize the png without loosing the transparency of the image.

**Comment by vseventer** [comment]
I am able to reproduce, however, this appears to be a bug with [sharp](https://github.com/lovell/sharp/) itself, not the CLI.

Script to reproduce (assuming your image is called "input.png", then "output.png" will not have the proper alpha channel):
```js
const sharp = require('sharp');
sharp('./input.png').toFile('./output.png');
```

As a sidenote, `--optimize` does not apply to PNGs, you're probably looking for `--compressionLevel`.

**Comment by janaagaard75** [comment]
Thanks a lot for looking into this. And thanks for the clarification about `--optimize`. I haven't yet figured out exactly what parameters `expo-optimize` is using.

I've created a issue on the `sharp` repository, <https://github.com/lovell/sharp/issues/2013>, so I'm closing this one.

**Comment by janaagaard75** [comment]
Sorry for opening up this bug again, but [Sharp v0.24.0 har just been released](https://www.npmjs.com/package/sharp), at it include a fix for https://github.com/lovell/sharp/issues/2013, so now `sharp-cli` has to be updated to reference this version.

Would you prefer that I make a pull request with the required change and updates to the changelog, or would you rather make the change yourself, @vseventer?

How about changing `sharp-cli` to allow patch updates of `sharp`, i.e. adding a tilde before the version number? It seems that Sharp is bumping the minor version number whenever there are breaking changes.

**Comment by vseventer** [comment]
Feel free to open a PR! Typically, the version of sharp is locked as each new CLI version adds support for the new sharp commands or options. I see this is a bit problematic when it comes to bug fixes, but I can always put a release out quickly.

**Comment by janaagaard75** [comment]
As stated in the other issue, I don't like messing with the global libraries on my computer, because I do not know or understand what consequences that might have. (Could I be breaking something else? Do I need to update them manually from know on?)

So I will close this, and hope that someone else has the time to create a pull request with an updated version of `sharp`.
