### ISSUE TITLE
Resize not working without a non-option argument contradicting official example

### ISSUE THREAD

**Issue by KasparEtter** [vseventer/sharp-cli#35]
Running `sharp resize --help` gives me as the first example:

```
Examples:
  sharp resize --height 100                 The output will be 100 pixels high,
                                            auto-scaled width
```

However, if I try this like `sharp resize --height 100 -i input.jpg -o output.jpg`, I get:

```
Not enough non-option arguments: got 0, need at least 1

Specify --help for available options
```

Either the example should be removed or resize should also work without non-option arguments. Personally, I'd prefer the latter.

**Comment by NicoHof** [comment]
@KasparEtter Hi! I tried to do the same I think.
I want to resize some images to the same height and keep the width auto-scaled to not cut off anything.

Its not documented but it works if you specify 0 as width. So this did the job for me:

`sharp -i './*.png' -o ./out resize 0 64`

I get all images with height 64 and width auto.

Hope this helps!
