### ISSUE TITLE
resize.fit 

### ISSUE THREAD

**Issue by pavelloz** [vseventer/sharp-cli#44]
Hey,

Ive been trying to debug my sharp implementation with your tool but i cant find one thing - `fit`

Its documented here: https://sharp.pixelplumbing.com/api-resize#resize

Im using `fit: inside` in my app but i dont know where to specify it when using the cli.

Thanks for your help :)

**Comment by vseventer** [comment]
Run `sharp resize --help` and you will see how to use the `--fit` option.

**Comment by pavelloz** [comment]
Thank you :)
