### ISSUE TITLE
Does it support avif in future?

### ISSUE THREAD

**Issue by sprabowo** [vseventer/sharp-cli#47]
Hi @vseventer,

right now, sharp has output option "avif" [https://sharp.pixelplumbing.com/api-output](https://sharp.pixelplumbing.com/api-output). could you help support this output in cli?

Thanks

**Comment by vseventer** [comment]
@sprabowo I'm lagging a bit behind compared to `sharp`, so when I get a chance to update the commands this will get added in.

**Comment by kiril-daskalov** [comment]
Hello!

I need AVIF sharp dependency to v0.28 to support AVIF format. 

@sprabowo I guess it is not just bumping package version and updating documentation?

**Comment by vseventer** [comment]
Please track process of #66 for AVIF support - I will close this one out once released.

**Comment by vseventer** [comment]
This has now been released.
