### ISSUE TITLE
Does not Install on ARM64 M1 Apple Silicone

### ISSUE THREAD

**Issue by chrisspiegl** [vseventer/sharp-cli#63]
Hello, I just found this package and tried installing on my M1 MacBook Pro.

It failed because Sharp in version 0.25.4 does not have ARM64 support.

However, I have used Sharp in version 0.30.3 in other projects which does have ARM64 support.

Can we just update the dependency for this library and release a new version or is there more work needed?

**Comment by basicserge** [comment]
Hi. I had same issue. This SO answer helped me on my M1 https://stackoverflow.com/a/67566332

**Comment by vseventer** [comment]
Fixed in v2.0.0 - see #61.
