### ISSUE TITLE
multiyargs@1.0.0: The engine "yargs" appears to be invalid.

### ISSUE THREAD

**Issue by davidrobin** [vseventer/sharp-cli#7]
Hello,

When I install your package or after install it when I do an upgrade, I have this warning in the shell:
"warning multiyargs@1.0.0: The engine "yargs" appears to be invalid."

I am using Yarn package manager instead of NPM.

Yarn 0.24.6
NodeJS 7.10.0
macOS Sierra 10.12.4

Could you check why this warning appears?

Regards

**Comment by vseventer** [comment]
Think it's because yarn validates the engine field, and yargs isn't really
an engine like node for example is.

It shouldn't stop you from installing and using the package afaik.
