### ISSUE TITLE
Proposal: Add `--animated` Global Option

### ISSUE THREAD

**Issue by leafac** [vseventer/sharp-cli#79]
Hi @vseventer,

First, thanks for this project. I find it very handy.

Second, I propose that we add a `--animated` Global Option. It’s an option given by [sharp](https://sharp.pixelplumbing.com/api-constructor) and it amounts to the same as `--pages -1`, but it’s a bit more descriptive.

I found some references to such a flag in the codebase, but couldn’t get it work. I tried putting `--animated` in many places on the command and the only one that didn’t complain about an unknown parameter was `sharp-cli -i animated.gif animated -o animated.webp`, but even then the output file wasn’t animated.

Thanks in advance.

**Comment by vseventer** [comment]
The `--animated` flag only applies to the `composite` command currently. It makes sense to have this available top-level.

**Comment by vseventer** [comment]
Released in v4.1.0.
