### ISSUE TITLE
Usage on Windows

### ISSUE THREAD

**Issue by andrekosak** [vseventer/sharp-cli#8]
Hello, i have one more question regarding Windows. I have Node 6 here, but i cannot manage how to use the cli properly. The point is, that it creates the new image in the same folder, and NOT uses the folder path i passed as "-o" parameter. See my output:

```
Admin@DESKTOP-RLI0V1T MINGW64 /d/Site/maerchen (master)
$ sharp -i ./static/images/* -o ./out resize 1500 0
D:%5CSite%5Cmaerchen%5Cout
D:%5CSite%5Cmaerchen%5Cout
```

So it's creating new files with wrong names in folder where i stand.
I have tried using the "Git Bash" and "Cmder". Result is the same.

Would someone have a hint for me?

**Comment by vseventer** [comment]
Hi @andrekosak, can you try running the command for a single input file only (without using `*`). I'm wondering whether Windows might interpret the asterisk differently, messing up the CLI.

**Comment by andrekosak** [comment]
i have tested it too, but no luck. then i gave up. now i am using docker to resize images on Windows: mount the folder and than to the stuff inside of container.

**Comment by Peilin-D** [comment]
I'm also having this problem.

**Comment by vseventer** [comment]
@andrekosak @Peilin-D Thank you for reporting, and apologies for the late fix.

**Comment by vseventer** [comment]
@nltesown You need to specify the output pattern - see https://github.com/vseventer/sharp-cli/issues/13#issuecomment-445133778

**Comment by nltesown** [comment]
Which gives:

    sharp -i ./*.tif -o ./output/{name}.jpg -f jpg

It works! Thanks a lot!
