### ISSUE TITLE
How to rasterize SVGs on PNG with specific width/height?

### ISSUE THREAD

**Issue by vico93** [vseventer/sharp-cli#86]
Hi! I'm updating [my scripts](https://github.com/vico93/svg-to-winico) to generate Windows ICOs from .SVGs, and decided to give sharp-cli (and [to-ico-cli](https://github.com/kevva/to-ico-cli) as well) a try.

Before I was using librsvg2 to do the rastering part, but to reduce the number of tools needed to my script (and to rely only on node.js-based tools) i would like to do it using sharp-cli itself.

The command i was using is `rsvg-convert "input.svg" -w 256 -h 256 -o output_256.png`

Also can sharp-cli also do multi-size .ico like to-ico-cli do? If yes, the script will only use sharp for the whole process 🎉

Btw, thanks for any help!

**Comment by vseventer** [comment]
> Hi! I'm updating [my scripts](https://github.com/vico93/svg-to-winico) to generate Windows ICOs from .SVGs, and decided to give sharp-cli (and [to-ico-cli](https://github.com/kevva/to-ico-cli) as well) a try.
> 
> Before I was using librsvg2 to do the rastering part, but to reduce the number of tools needed to my script (and to rely only on node.js-based tools) i would like to do it using sharp-cli itself.
> 
> The command i was using is `rsvg-convert "input.svg" -w 256 -h 256 -o output_256.png`
> 
> Also can sharp-cli also do multi-size .ico like to-ico-cli do? If yes, the script will only use sharp for the whole process 🎉
> 
> Btw, thanks for any help!

Have you tried this using the underlying sharp module using Node (not CLI) by any chance?

**Comment by vico93** [comment]
> > Hi! I'm updating [my scripts](https://github.com/vico93/svg-to-winico) to generate Windows ICOs from .SVGs, and decided to give sharp-cli (and [to-ico-cli](https://github.com/kevva/to-ico-cli) as well) a try.
> > Before I was using librsvg2 to do the rastering part, but to reduce the number of tools needed to my script (and to rely only on node.js-based tools) i would like to do it using sharp-cli itself.
> > The command i was using is `rsvg-convert "input.svg" -w 256 -h 256 -o output_256.png`
> > Also can sharp-cli also do multi-size .ico like to-ico-cli do? If yes, the script will only use sharp for the whole process 🎉
> > Btw, thanks for any help!
> 
> Have you tried this using the underlying sharp module using Node (not CLI) by any chance?

Sorry the late response, but no. I want to use CLI because i'm updating an old bash file to get ridden of imagemagick and other legacy software to make the conversion. I don't want to make a node package just for that.

**Comment by vseventer** [comment]
Does the `resize` command (maybe in combination with `density` input option) give you anything close to what you want?

**Comment by vico93** [comment]
> Does the `resize` command (maybe in combination with `density` input option) give you anything close to what you want?

i will look into it soon and then report if it worked (if not i can reopen the issue). Thank you for your support!
